// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mike05.Models;

namespace Mike05.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mike05.Models.Book", b =>
            {
                b.Property<int>("BookId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("AuthorFirst")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("AuthorLast")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("AuthorMiddle")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Classification")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CoverImg")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ISBN")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Price")
                    .HasColumnType("float");

                b.Property<string>("Publisher")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TotalPages")
                    .HasColumnType("int");

                b.HasKey("BookId");

                b.ToTable("Books");
            });
#pragma warning restore 612, 618
        }
    }
}
